# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - student-performace-indicator

on:
  push:
    branches:
      - ankita-dev-2
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://testdockerankita.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_0a0e86b8fe8f4947ba350082448f4d33 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_97c670da69e24fa3b183ca287633fd5e }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: testdockerankita.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_0a0e86b8fe8f4947ba350082448f4d33 }}/testdockerankita/irisflask:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'student-performace-indicator'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_e3d109d2a7a847c2a86628c67daf6a72 }}
        images: 'testdockerankita.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_0a0e86b8fe8f4947ba350082448f4d33 }}/testdockerankita/irisflask:${{ github.sha }}'